/**
 * @file actions 的 type name
 * author chaohui
 */

export const GET_PLAN_INFO = 'GET_PLAN_INFO'
export const GET_INTER_LIST = 'GET_INTER_LIST'
export const GET_CONTROL_ROAD = 'GET_CONTROL_ROAD'
export const GET_CONTROL_COUNT = 'GET_CONTROL_COUNT'
export const GET_PLAN_TIME = 'GET_PLAN_TIME'
export const GET_CONTROL_STATUS = 'GET_CONTROL_STATUS'
export const GET_REAL_STATUS = 'GET_REAL_STATUS'
export const GET_FAULT_STATISTICS = 'GET_FAULT_STATISTICS'
export const GET_INTER_INFO = 'GET_INTER_INFO'
export const GET_SINGAL_INFO = 'GET_SINGAL_INFO'
export const GET_ISSIGNALING = 'GET_ISSIGNALING'
export const GET_PLAN_STAGE = 'GET_PLAN_STAGE'
export const GET_PRIMITIVE_INUTUITYPE = 'GET_PRIMITIVE_INUTUITYPE'
export const GET_MONITOR_INFO = 'GET_MONITOR_INFO'
export const GET_PRIMITIVE_BASEMAPIMG = 'GET_PRIMITIVE_BASEMAPIMG'
// export const GET_PRIMITIVE_UICONFIG = 'GET_PRIMITIVE_UICONFIG'
export const GET_PRIMITIVE_UPDATEBASEMAP = 'GET_PRIMITIVE_UPDATEBASEMAP'
export const GET_PRIMITIVE_UPLOAD = 'GET_PRIMITIVE_UPLOAD'
export const GET_PRIMITIVE_EDITDEVICEINFOPO = 'GET_PRIMITIVE_EDITDEVICEINFOPO'
export const GET_PRIMITIVE_SHOWDEVICEINFO = 'GET_PRIMITIVE_SHOWDEVICEINFO'
export const GET_PRIMITIVE_SHOWUILIST = 'GET_PRIMITIVE_SHOWUILIST'
