export const API_TREEDATA = '/dws/interSignal/getInterDataTree'
export const API_INTERFLOW = '/dws/appExtend/getInterFlow'
export const API_INTERQUEUE = '/dws/appExtend/getInterQueueLenth'
export const API_INTERSATURATION = '/dws/appExtend/getInterSaturation'
export const API_INTERSTOPNUM = '/dws/appExtend/getInterStopNum'
export const API_INTERRATIO = '/dws/appExtend/getInterGreenUtilizeRatio'
export const API_INTERPHASEODDS = '/dws/appExtend/getInterPhasePassOdds'
export const API_INTERCIRCULAR = '/app/getTimeIntervalCongestion'