/**
 * @file 路口管理 action type
 */

export const GET_UNITINTER_INFO = 'GET_UNITINTER_INFO'
export const GET_UNIT_CONTROLSYS = 'GET_UNIT_CONTROLSYS'
export const GET_UNIT_INTERTYPE = 'GET_UNIT_INTERTYPE'
export const GET_UNIT_DEVICETYPE = 'GET_UNIT_DEVICETYPE'
export const GET_MANAGEMENT_UNIT = 'GET_MANAGEMENT_UNIT'
export const GET_UNIT_DIRECTION = 'GET_UNIT_DIRECTION'
